Chatbot/chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'post/$', views.post, name='post'),
    url(r'^messages/$', views.messages, name='messages'),
]

Chatbot/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('chat.urls', namespace="chat")),
]

Chatbot/chat/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Chat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=255)
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING,)
    human_bot = models.BooleanField(default=True)
    def __str__(self):
        return self.message

Chatbot/chat/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from .my_sql_connect import database_fetch , json_html
from .chart import chart_display
from chat.models import Chat
from .aiml_try import aiml_generate
from .lsa import lsa_fetch
from .pre_process import preprocess_data
import aiml

aiml_handle = aiml.Kernel()
response_queue = ""
cant_answer_count = 0

def home(request):
    global aiml_handle
    Chat.objects.all().delete()
    aiml_generate(aiml_handle)
    chats = Chat.objects.all()
    ctx = {
        'home': 'active',
        'chat': chats
    }

    msg = "count of complaints"
    response = aiml_handle.respond(preprocess_data(msg))
    result_list = database_fetch(response[1:]);
    if request.user.is_authenticated():
        if len(result_list) != 0:
            msg =  "Hi " +str(request.user) +  " we have recieved <span class=\"badge\" style=\"float: none;background:red;\">" + str(result_list[0]["count(*)"]) + "</span> complaints."
            chat_message = Chat(user=request.user, message=msg,human_bot=False)
            chat_message.save()

    if request.user.is_authenticated():
        return render(request, 'chat.html', ctx)
    else:
        return render(request, 'base.html', None)


def post(request):
    global aiml_handle,response_queue,cant_answer_count
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        print('Our value = ', msg)

        chat_message = Chat(user=request.user, message=msg,human_bot=True)
        if msg != '':
            chat_message.save()
        
        response = aiml_handle.respond(preprocess_data(msg))
        if  response == '':
            response_queue = response_queue + " " + msg
            cant_answer_count = cant_answer_count + 1
            found= 0
            if cant_answer_count > 2:
                lsa_Keywords = lsa_fetch(response_queue)
                #print lsa_Keywords
                for keyword_Lsa in lsa_Keywords:
                    response = aiml_handle.respond(preprocess_data("Lsa "+keyword_Lsa))
                    print ("Lsa = "+ response)
                    if(response!=''):
                        found = 1
                        response_queue = ""
                        cant_answer_count = 0
                        break
            if found == 0:   
                    result = ":( Sorry , response Not Found Can you Elaborate !!!"
        
        if(response!=''):
            response_queue = ""
            cant_answer_count = 0
            result = response
            if response[0] == '@':
                result_list = database_fetch(response[1:]);
                result = json_html(result_list)
            elif response[0] =='$':
                result= chart_display(response[1:]);
        
        chat_message2 = Chat(user=request.user, message=result,human_bot=False)
        chat_message2.save()

        return JsonResponse({'msg': msg, 'user': chat_message.user.username})
    else:
        return HttpResponse('Request must be POST.')


def messages(request):
    chat = Chat.objects.all()
    return render(request, 'messages.html', {'chat': chat})

Chatbot/templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load account %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat</title>
    <style>
        li:nth-child(even) { background:  #f5f5f5; }
        li:nth-child(odd) { background: white;}

        table {
          border-collapse: collapse;
          width: 100%;
        }
        
        th, td {
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even){background-color: #f2f2f2}
        
        th {
          background-color: rgb(252, 122, 0);
          color: white;
        }
    </style>
    {% include "head_css.html" %}
    {% block extra_css %}{% endblock %}
    {% block extra_js %}{% endblock %}
</head>
<body>
{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"Chat</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><p class="navbar-text">Signed in as <b>{{ user.username }}</b></p></li>
                    {% else %}
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_anonymous %}
                        <a href="/accounts/login/">
                            <button type="button" class="btn navbar-btn btn-success">Sign in</button>
                        </a>
                        <a href="/accounts/signup/">
                            <button type="button" class="btn navbar-btn btn-success">Register</button>
                        </a>
                    {% else %}
                        <a href="/accounts/logout/">
                            <button type="button" class="btn btn-danger navbar-btn">Log out</button>
                        </a>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
{% endblock navbar %}



{% block content %}
    <header class="body-header">
        <div class="body-header__title">
            <h1 class="text-center">Chatbot</h1>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <p class="lead text-center">Login before using chat!</p>
        </div>
    </div>

{% endblock %}


</div>


<script src="{% static 'chat/js/jquery-1.12.3.js' %}"></script>
<script src="{% static 'chat/js/bootstrap.min.js' %}"></script>
<script src="{% static 'chat/js/script_new.js' %}"></script>
</body>
</html>

Chatbot/templates/chat.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div id="chat-body" class="panel panel-default">
    <div class="panel-heading">ChatBot</div>
    <div id="msg-list-div" class="panel-body">
      <ul id="msg-list" class="list-group">
        {% for obj in chat %} {% if obj.human_bot %}
        <li class="text-right list-group-item">{{ obj.message | safe }}</li>
        {% else %}
        <li class="text-left list-group-item">{{ obj.message | safe }}</li>
        {% endif %} {% empty %}
        <li class="text-right list-group-item">No messages yet!</li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <form
    id="chat-form"
    method="post"
    action="{% url 'chat:post' %}"
    data-spy="affix"
    data-offset-bottom="10"
  >
    {% csrf_token %}
    <div id="chat-bottom" class="input-group">
      <input type="text" id="chat-msg" name="chat-msg" class="form-control" />
      <span class="input-group-btn">
        <input class="btn btn-default" id="send" type="submit" value="Send" />
      </span>
    </div>
  </form>
</div>
{% endblock content %}

Chatbot/templates/head_css.html
{% load staticfiles %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'chat/css/bootstrap.min.css' %}"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'chat/css/style.css' %}"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css"
/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>

Chatbot/templates/messages.html
{% for obj in chat %} {% if obj.human_bot %}
<li class="text-right list-group-item">{{ obj.message | safe }}</li>
{% else %}
<li class="text-left list-group-item">{{ obj.message | safe }}</li>
{% endif %} {% empty %}
<li class="text-right list-group-item">No messages yet!</li>
{% endfor %}